# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# project.py
# Created on: 2015-03-02 23:36:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
sample_shape = "sample_shape"
da_centre_shp = "C:\\Users\\carl\\Desktop\\webapp\\vancouver_features\\da_centre.shp"

# Process: Feature To Point
arcpy.FeatureToPoint_management(sample_shape, da_centre_shp, "CENTROID")

